{
  "affected_release": null,
  "package_state": [
    {
      "product_name": "Red Hat Ansible Automation Platform 1.2",
      "fix_state": "Not affected",
      "package_name": "ansible-tower",
      "cpe": "cpe:/a:redhat:ansible_automation_platform"
    },
    {
      "product_name": "Red Hat Ansible Automation Platform 2",
      "fix_state": "Not affected",
      "package_name": "ansible-lint",
      "cpe": "cpe:/a:redhat:ansible_automation_platform:2"
    },
    {
      "product_name": "Red Hat Ansible Automation Platform 2",
      "fix_state": "Not affected",
      "package_name": "ansible-navigator",
      "cpe": "cpe:/a:redhat:ansible_automation_platform:2"
    },
    {
      "product_name": "Red Hat Ansible Automation Platform 2",
      "fix_state": "Not affected",
      "package_name": "automation-controller",
      "cpe": "cpe:/a:redhat:ansible_automation_platform:2"
    },
    {
      "product_name": "Red Hat Ansible Automation Platform 2",
      "fix_state": "Not affected",
      "package_name": "python3x-ansible-compat",
      "cpe": "cpe:/a:redhat:ansible_automation_platform:2"
    },
    {
      "product_name": "Red Hat Ansible Automation Platform 2",
      "fix_state": "Not affected",
      "package_name": "python3x-cryptography",
      "cpe": "cpe:/a:redhat:ansible_automation_platform:2"
    },
    {
      "product_name": "Red Hat Ansible Automation Platform 2",
      "fix_state": "Not affected",
      "package_name": "python-ansible-compat",
      "cpe": "cpe:/a:redhat:ansible_automation_platform:2"
    },
    {
      "product_name": "Red Hat Ansible Automation Platform 2",
      "fix_state": "Not affected",
      "package_name": "python-cryptography",
      "cpe": "cpe:/a:redhat:ansible_automation_platform:2"
    },
    {
      "product_name": "Red Hat Certification for Red Hat Enterprise Linux 6",
      "fix_state": "Not affected",
      "package_name": "redhat-certification-backend",
      "cpe": "cpe:/a:redhat:certifications:1::el6"
    },
    {
      "product_name": "Red Hat Certification for Red Hat Enterprise Linux 8",
      "fix_state": "Not affected",
      "package_name": "redhat-certification-baremetal-container",
      "cpe": "cpe:/a:redhat:certifications:1::el8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Not affected",
      "package_name": "python-adal",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Not affected",
      "package_name": "python-cryptography",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Not affected",
      "package_name": "python3.11-cryptography",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Not affected",
      "package_name": "python39:3.9/python-cryptography",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Not affected",
      "package_name": "python-cryptography",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 9",
      "fix_state": "Not affected",
      "package_name": "fence-agents",
      "cpe": "cpe:/o:redhat:enterprise_linux:9"
    },
    {
      "product_name": "Red Hat Enterprise Linux 9",
      "fix_state": "Not affected",
      "package_name": "python3.11-cryptography",
      "cpe": "cpe:/o:redhat:enterprise_linux:9"
    },
    {
      "product_name": "Red Hat Enterprise Linux 9",
      "fix_state": "Not affected",
      "package_name": "python-cryptography",
      "cpe": "cpe:/o:redhat:enterprise_linux:9"
    },
    {
      "product_name": "Red Hat Quay 3",
      "fix_state": "Not affected",
      "package_name": "quay/quay-rhel8",
      "cpe": "cpe:/a:redhat:quay:3"
    },
    {
      "product_name": "Red Hat Satellite 6",
      "fix_state": "Not affected",
      "package_name": "ansiblerole-foreman_scap_client",
      "cpe": "cpe:/a:redhat:satellite:6"
    },
    {
      "product_name": "Red Hat Satellite 6",
      "fix_state": "Not affected",
      "package_name": "python-cryptography",
      "cpe": "cpe:/a:redhat:satellite:6"
    },
    {
      "product_name": "Red Hat Satellite 6",
      "fix_state": "Not affected",
      "package_name": "python-types-cryptography",
      "cpe": "cpe:/a:redhat:satellite:6"
    },
    {
      "product_name": "Red Hat Satellite 6",
      "fix_state": "Not affected",
      "package_name": "tfm-pulpcore-python-cryptography",
      "cpe": "cpe:/a:redhat:satellite:6"
    },
    {
      "product_name": "Red Hat Software Collections",
      "fix_state": "Not affected",
      "package_name": "rh-python38-python-cryptography",
      "cpe": "cpe:/a:redhat:rhel_software_collections:3"
    },
    {
      "product_name": "Red Hat Update Infrastructure 4 for Cloud Providers",
      "fix_state": "Not affected",
      "package_name": "python-cryptography",
      "cpe": "cpe:/a:redhat:rhui:4::el8"
    },
    {
      "product_name": "Red Hat Update Infrastructure 4 for Cloud Providers",
      "fix_state": "Not affected",
      "package_name": "python-types-cryptography",
      "cpe": "cpe:/a:redhat:rhui:4::el8"
    }
  ],
  "threat_severity": "Moderate",
  "public_date": "2023-07-15T08:00:00Z",
  "bugzilla": {
    "description": "python-cryptography: SSH certificate encoding/parsing incompatibility with OpenSSH",
    "id": "2231271",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2231271"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "7.5",
    "cvss3_scoring_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
    "status": "draft"
  },
  "iava": "",
  "cwe": "CWE-295",
  "statement": "OpenSSH certificate parsing was introduced in python-cryptography v40.0.0 and fixed in upstream release v41.0.2. Since, Red Hat Enterprise Linux - 7, 8, 9 ships lower versions of python-cryptography (releases \u003c v40.0.0), those are not affected by this CVE.",
  "acknowledgement": "",
  "name": "CVE-2023-38325",
  "document_distribution": "",
  "details": [
    "The cryptography package before 41.0.2 for Python mishandles SSH certificates that have critical options."
  ],
  "references": [
    "https://www.cve.org/CVERecord?id=CVE-2023-38325\nhttps://nvd.nist.gov/vuln/detail/CVE-2023-38325\nhttps://github.com/advisories/GHSA-cf7p-gm2m-833m"
  ]
}