{
  "affected_release": null,
  "package_state": [
    {
      "product_name": "Red Hat Enterprise Linux 6",
      "fix_state": "Out of support scope",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:6"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Out of support scope",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Out of support scope",
      "package_name": "kernel-rt",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Out of support scope",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Out of support scope",
      "package_name": "kernel-rt",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 9",
      "fix_state": "Fix deferred",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:9"
    },
    {
      "product_name": "Red Hat Enterprise Linux 9",
      "fix_state": "Fix deferred",
      "package_name": "kernel-rt",
      "cpe": "cpe:/o:redhat:enterprise_linux:9"
    }
  ],
  "threat_severity": "Moderate",
  "public_date": "2025-05-02T00:00:00Z",
  "bugzilla": {
    "description": "kernel: ext4: fix WARNING in ext4_update_inline_data",
    "id": "2363785",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2363785"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "5.5",
    "cvss3_scoring_vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
    "status": "draft"
  },
  "iava": "",
  "cwe": "",
  "statement": "",
  "acknowledgement": "",
  "name": "CVE-2023-53100",
  "document_distribution": "",
  "details": [
    "In the Linux kernel, the following vulnerability has been resolved:\next4: fix WARNING in ext4_update_inline_data\nSyzbot found the following issue:\nEXT4-fs (loop0): mounted filesystem 00000000-0000-0000-0000-000000000000 without journal. Quota mode: none.\nfscrypt: AES-256-CTS-CBC using implementation \"cts-cbc-aes-aesni\"\nfscrypt: AES-256-XTS using implementation \"xts-aes-aesni\"\n------------[ cut here ]------------\nWARNING: CPU: 0 PID: 5071 at mm/page_alloc.c:5525 __alloc_pages+0x30a/0x560 mm/page_alloc.c:5525\nModules linked in:\nCPU: 1 PID: 5071 Comm: syz-executor263 Not tainted 6.2.0-rc1-syzkaller #0\nHardware name: Google Google Compute Engine/Google Compute Engine, BIOS Google 10/26/2022\nRIP: 0010:__alloc_pages+0x30a/0x560 mm/page_alloc.c:5525\nRSP: 0018:ffffc90003c2f1c0 EFLAGS: 00010246\nRAX: ffffc90003c2f220 RBX: 0000000000000014 RCX: 0000000000000000\nRDX: 0000000000000028 RSI: 0000000000000000 RDI: ffffc90003c2f248\nRBP: ffffc90003c2f2d8 R08: dffffc0000000000 R09: ffffc90003c2f220\nR10: fffff52000785e49 R11: 1ffff92000785e44 R12: 0000000000040d40\nR13: 1ffff92000785e40 R14: dffffc0000000000 R15: 1ffff92000785e3c\nFS:  0000555556c0d300(0000) GS:ffff8880b9800000(0000) knlGS:0000000000000000\nCS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033\nCR2: 00007f95d5e04138 CR3: 00000000793aa000 CR4: 00000000003506f0\nDR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000\nDR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400\nCall Trace:\n\u003cTASK\u003e\n__alloc_pages_node include/linux/gfp.h:237 [inline]\nalloc_pages_node include/linux/gfp.h:260 [inline]\n__kmalloc_large_node+0x95/0x1e0 mm/slab_common.c:1113\n__do_kmalloc_node mm/slab_common.c:956 [inline]\n__kmalloc+0xfe/0x190 mm/slab_common.c:981\nkmalloc include/linux/slab.h:584 [inline]\nkzalloc include/linux/slab.h:720 [inline]\next4_update_inline_data+0x236/0x6b0 fs/ext4/inline.c:346\next4_update_inline_dir fs/ext4/inline.c:1115 [inline]\next4_try_add_inline_entry+0x328/0x990 fs/ext4/inline.c:1307\next4_add_entry+0x5a4/0xeb0 fs/ext4/namei.c:2385\next4_add_nondir+0x96/0x260 fs/ext4/namei.c:2772\next4_create+0x36c/0x560 fs/ext4/namei.c:2817\nlookup_open fs/namei.c:3413 [inline]\nopen_last_lookups fs/namei.c:3481 [inline]\npath_openat+0x12ac/0x2dd0 fs/namei.c:3711\ndo_filp_open+0x264/0x4f0 fs/namei.c:3741\ndo_sys_openat2+0x124/0x4e0 fs/open.c:1310\ndo_sys_open fs/open.c:1326 [inline]\n__do_sys_openat fs/open.c:1342 [inline]\n__se_sys_openat fs/open.c:1337 [inline]\n__x64_sys_openat+0x243/0x290 fs/open.c:1337\ndo_syscall_x64 arch/x86/entry/common.c:50 [inline]\ndo_syscall_64+0x3d/0xb0 arch/x86/entry/common.c:80\nentry_SYSCALL_64_after_hwframe+0x63/0xcd\nAbove issue happens as follows:\next4_iget\next4_find_inline_data_nolock -\u003ei_inline_off=164 i_inline_size=60\next4_try_add_inline_entry\n__ext4_mark_inode_dirty\next4_expand_extra_isize_ea -\u003ei_extra_isize=32 s_want_extra_isize=44\next4_xattr_shift_entries\n-\u003eafter shift i_inline_off is incorrect, actually is change to 176\next4_try_add_inline_entry\next4_update_inline_dir\nget_max_inline_xattr_value_size\nif (EXT4_I(inode)-\u003ei_inline_off)\nentry = (struct ext4_xattr_entry *)((void *)raw_inode +\nEXT4_I(inode)-\u003ei_inline_off);\nfree += EXT4_XATTR_SIZE(le32_to_cpu(entry-\u003ee_value_size));\n-\u003eAs entry is incorrect, then 'free' may be negative\next4_update_inline_data\nvalue = kzalloc(len, GFP_NOFS);\n-\u003e len is unsigned int, maybe very large, then trigger warning when\n'kzalloc()'\nTo resolve the above issue we need to update 'i_inline_off' after\n'ext4_xattr_shift_entries()'.  We do not need to set\nEXT4_STATE_MAY_INLINE_DATA flag here, since ext4_mark_inode_dirty()\nalready sets this flag if needed.  Setting EXT4_STATE_MAY_INLINE_DATA\nwhen it is needed may trigger a BUG_ON in ext4_writepages()."
  ],
  "references": [
    "https://www.cve.org/CVERecord?id=CVE-2023-53100\nhttps://nvd.nist.gov/vuln/detail/CVE-2023-53100\nhttps://lore.kernel.org/linux-cve-announce/2025050223-CVE-2023-53100-f480@gregkh/T"
  ]
}