{
  "affected_release": null,
  "package_state": [
    {
      "product_name": "Red Hat Enterprise Linux 6",
      "fix_state": "Out of support scope",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:6"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Out of support scope",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Out of support scope",
      "package_name": "kernel-rt",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Out of support scope",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Out of support scope",
      "package_name": "kernel-rt",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 9",
      "fix_state": "Fix deferred",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:9"
    },
    {
      "product_name": "Red Hat Enterprise Linux 9",
      "fix_state": "Fix deferred",
      "package_name": "kernel-rt",
      "cpe": "cpe:/o:redhat:enterprise_linux:9"
    }
  ],
  "threat_severity": "Moderate",
  "public_date": "2025-05-02T00:00:00Z",
  "bugzilla": {
    "description": "kernel: ext4: fix task hung in ext4_xattr_delete_inode",
    "id": "2363736",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2363736"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "5.5",
    "cvss3_scoring_vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
    "status": "draft"
  },
  "iava": "",
  "cwe": "",
  "statement": "",
  "acknowledgement": "",
  "name": "CVE-2023-53089",
  "document_distribution": "",
  "details": [
    "In the Linux kernel, the following vulnerability has been resolved:\next4: fix task hung in ext4_xattr_delete_inode\nSyzbot reported a hung task problem:\n==================================================================\nINFO: task syz-executor232:5073 blocked for more than 143 seconds.\nNot tainted 6.2.0-rc2-syzkaller-00024-g512dee0c00ad #0\n\"echo 0 \u003e /proc/sys/kernel/hung_task_timeout_secs\" disables this message.\ntask:syz-exec232 state:D stack:21024 pid:5073 ppid:5072 flags:0x00004004\nCall Trace:\n\u003cTASK\u003e\ncontext_switch kernel/sched/core.c:5244 [inline]\n__schedule+0x995/0xe20 kernel/sched/core.c:6555\nschedule+0xcb/0x190 kernel/sched/core.c:6631\n__wait_on_freeing_inode fs/inode.c:2196 [inline]\nfind_inode_fast+0x35a/0x4c0 fs/inode.c:950\niget_locked+0xb1/0x830 fs/inode.c:1273\n__ext4_iget+0x22e/0x3ed0 fs/ext4/inode.c:4861\next4_xattr_inode_iget+0x68/0x4e0 fs/ext4/xattr.c:389\next4_xattr_inode_dec_ref_all+0x1a7/0xe50 fs/ext4/xattr.c:1148\next4_xattr_delete_inode+0xb04/0xcd0 fs/ext4/xattr.c:2880\next4_evict_inode+0xd7c/0x10b0 fs/ext4/inode.c:296\nevict+0x2a4/0x620 fs/inode.c:664\next4_orphan_cleanup+0xb60/0x1340 fs/ext4/orphan.c:474\n__ext4_fill_super fs/ext4/super.c:5516 [inline]\next4_fill_super+0x81cd/0x8700 fs/ext4/super.c:5644\nget_tree_bdev+0x400/0x620 fs/super.c:1282\nvfs_get_tree+0x88/0x270 fs/super.c:1489\ndo_new_mount+0x289/0xad0 fs/namespace.c:3145\ndo_mount fs/namespace.c:3488 [inline]\n__do_sys_mount fs/namespace.c:3697 [inline]\n__se_sys_mount+0x2d3/0x3c0 fs/namespace.c:3674\ndo_syscall_x64 arch/x86/entry/common.c:50 [inline]\ndo_syscall_64+0x3d/0xb0 arch/x86/entry/common.c:80\nentry_SYSCALL_64_after_hwframe+0x63/0xcd\nRIP: 0033:0x7fa5406fd5ea\nRSP: 002b:00007ffc7232f968 EFLAGS: 00000202 ORIG_RAX: 00000000000000a5\nRAX: ffffffffffffffda RBX: 0000000000000003 RCX: 00007fa5406fd5ea\nRDX: 0000000020000440 RSI: 0000000020000000 RDI: 00007ffc7232f970\nRBP: 00007ffc7232f970 R08: 00007ffc7232f9b0 R09: 0000000000000432\nR10: 0000000000804a03 R11: 0000000000000202 R12: 0000000000000004\nR13: 0000555556a7a2c0 R14: 00007ffc7232f9b0 R15: 0000000000000000\n\u003c/TASK\u003e\n==================================================================\nThe problem is that the inode contains an xattr entry with ea_inum of 15\nwhen cleaning up an orphan inode \u003c15\u003e. When evict inode \u003c15\u003e, the reference\ncounting of the corresponding EA inode is decreased. When EA inode \u003c15\u003e is\nfound by find_inode_fast() in __ext4_iget(), it is found that the EA inode\nholds the I_FREEING flag and waits for the EA inode to complete deletion.\nAs a result, when inode \u003c15\u003e is being deleted, we wait for inode \u003c15\u003e to\ncomplete the deletion, resulting in an infinite loop and triggering Hung\nTask. To solve this problem, we only need to check whether the ino of EA\ninode and parent is the same before getting EA inode."
  ],
  "references": [
    "https://www.cve.org/CVERecord?id=CVE-2023-53089\nhttps://nvd.nist.gov/vuln/detail/CVE-2023-53089\nhttps://lore.kernel.org/linux-cve-announce/2025050219-CVE-2023-53089-b8c6@gregkh/T"
  ]
}