{
  "affected_release": null,
  "package_state": [
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Affected",
      "package_name": "tomcat",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Affected",
      "package_name": "pki-deps:10.6/pki-servlet-engine",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Affected",
      "package_name": "tomcat",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 9",
      "fix_state": "Affected",
      "package_name": "pki-servlet-engine",
      "cpe": "cpe:/o:redhat:enterprise_linux:9"
    },
    {
      "product_name": "Red Hat Enterprise Linux 9",
      "fix_state": "Affected",
      "package_name": "tomcat",
      "cpe": "cpe:/o:redhat:enterprise_linux:9"
    },
    {
      "product_name": "Red Hat JBoss Web Server 5",
      "fix_state": "Affected",
      "package_name": "tomcat",
      "cpe": "cpe:/a:redhat:jboss_enterprise_web_server:5"
    },
    {
      "product_name": "Red Hat JBoss Web Server 6",
      "fix_state": "Affected",
      "package_name": "tomcat",
      "cpe": "cpe:/a:redhat:jboss_enterprise_web_server:6"
    }
  ],
  "threat_severity": "Important",
  "public_date": "2024-09-23T00:00:00Z",
  "bugzilla": {
    "description": "tomcat: Denial of Service in Tomcat",
    "id": "2314686",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2314686"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "7.5",
    "cvss3_scoring_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
    "status": "draft"
  },
  "iava": "",
  "cwe": "CWE-400",
  "statement": "",
  "acknowledgement": "",
  "name": "CVE-2024-38286",
  "document_distribution": "",
  "details": [
    "A vulnerability was found in Tomcat. Under certain configurations on any platform, this flaw allows an attacker to cause an OutOfMemoryError by abusing the TLS handshake process."
  ],
  "references": [
    "https://www.cve.org/CVERecord?id=CVE-2024-38286\nhttps://nvd.nist.gov/vuln/detail/CVE-2024-38286\nhttps://lists.apache.org/thread/wms60cvbsz3fpbz9psxtfx8r41jl6d4s"
  ]
}