{
  "affected_release": null,
  "package_state": [
    {
      "product_name": "Red Hat Enterprise Linux 6",
      "fix_state": "Not affected",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:6"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Out of support scope",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Out of support scope",
      "package_name": "kernel-rt",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Out of support scope",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Out of support scope",
      "package_name": "kernel-rt",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 9",
      "fix_state": "Fix deferred",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:9"
    },
    {
      "product_name": "Red Hat Enterprise Linux 9",
      "fix_state": "Fix deferred",
      "package_name": "kernel-rt",
      "cpe": "cpe:/o:redhat:enterprise_linux:9"
    }
  ],
  "threat_severity": "Moderate",
  "public_date": "2025-05-01T00:00:00Z",
  "bugzilla": {
    "description": "kernel: Bluetooth: L2CAP: fix use-after-free in l2cap_conn_del()",
    "id": "2363428",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2363428"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "5.5",
    "cvss3_scoring_vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
    "status": "draft"
  },
  "iava": "",
  "cwe": "",
  "statement": "",
  "acknowledgement": "",
  "name": "CVE-2022-49909",
  "document_distribution": "",
  "details": [
    "In the Linux kernel, the following vulnerability has been resolved:\nBluetooth: L2CAP: fix use-after-free in l2cap_conn_del()\nWhen l2cap_recv_frame() is invoked to receive data, and the cid is\nL2CAP_CID_A2MP, if the channel does not exist, it will create a channel.\nHowever, after a channel is created, the hold operation of the channel\nis not performed. In this case, the value of channel reference counting\nis 1. As a result, after hci_error_reset() is triggered, l2cap_conn_del()\ninvokes the close hook function of A2MP to release the channel. Then\nl2cap_chan_unlock(chan) will trigger UAF issue.\nThe process is as follows:\nReceive data:\nl2cap_data_channel()\na2mp_channel_create()  ---\u003echannel ref is 2\nl2cap_chan_put()       ---\u003echannel ref is 1\nTriger event:\nhci_error_reset()\nhci_dev_do_close()\n...\nl2cap_disconn_cfm()\nl2cap_conn_del()\nl2cap_chan_hold()    ---\u003echannel ref is 2\nl2cap_chan_del()     ---\u003echannel ref is 1\na2mp_chan_close_cb() ---\u003echannel ref is 0, release channel\nl2cap_chan_unlock()  ---\u003eUAF of channel\nThe detailed Call Trace is as follows:\nBUG: KASAN: use-after-free in __mutex_unlock_slowpath+0xa6/0x5e0\nRead of size 8 at addr ffff8880160664b8 by task kworker/u11:1/7593\nWorkqueue: hci0 hci_error_reset\nCall Trace:\n\u003cTASK\u003e\ndump_stack_lvl+0xcd/0x134\nprint_report.cold+0x2ba/0x719\nkasan_report+0xb1/0x1e0\nkasan_check_range+0x140/0x190\n__mutex_unlock_slowpath+0xa6/0x5e0\nl2cap_conn_del+0x404/0x7b0\nl2cap_disconn_cfm+0x8c/0xc0\nhci_conn_hash_flush+0x11f/0x260\nhci_dev_close_sync+0x5f5/0x11f0\nhci_dev_do_close+0x2d/0x70\nhci_error_reset+0x9e/0x140\nprocess_one_work+0x98a/0x1620\nworker_thread+0x665/0x1080\nkthread+0x2e4/0x3a0\nret_from_fork+0x1f/0x30\n\u003c/TASK\u003e\nAllocated by task 7593:\nkasan_save_stack+0x1e/0x40\n__kasan_kmalloc+0xa9/0xd0\nl2cap_chan_create+0x40/0x930\namp_mgr_create+0x96/0x990\na2mp_channel_create+0x7d/0x150\nl2cap_recv_frame+0x51b8/0x9a70\nl2cap_recv_acldata+0xaa3/0xc00\nhci_rx_work+0x702/0x1220\nprocess_one_work+0x98a/0x1620\nworker_thread+0x665/0x1080\nkthread+0x2e4/0x3a0\nret_from_fork+0x1f/0x30\nFreed by task 7593:\nkasan_save_stack+0x1e/0x40\nkasan_set_track+0x21/0x30\nkasan_set_free_info+0x20/0x30\n____kasan_slab_free+0x167/0x1c0\nslab_free_freelist_hook+0x89/0x1c0\nkfree+0xe2/0x580\nl2cap_chan_put+0x22a/0x2d0\nl2cap_conn_del+0x3fc/0x7b0\nl2cap_disconn_cfm+0x8c/0xc0\nhci_conn_hash_flush+0x11f/0x260\nhci_dev_close_sync+0x5f5/0x11f0\nhci_dev_do_close+0x2d/0x70\nhci_error_reset+0x9e/0x140\nprocess_one_work+0x98a/0x1620\nworker_thread+0x665/0x1080\nkthread+0x2e4/0x3a0\nret_from_fork+0x1f/0x30\nLast potentially related work creation:\nkasan_save_stack+0x1e/0x40\n__kasan_record_aux_stack+0xbe/0xd0\ncall_rcu+0x99/0x740\nnetlink_release+0xe6a/0x1cf0\n__sock_release+0xcd/0x280\nsock_close+0x18/0x20\n__fput+0x27c/0xa90\ntask_work_run+0xdd/0x1a0\nexit_to_user_mode_prepare+0x23c/0x250\nsyscall_exit_to_user_mode+0x19/0x50\ndo_syscall_64+0x42/0x80\nentry_SYSCALL_64_after_hwframe+0x63/0xcd\nSecond to last potentially related work creation:\nkasan_save_stack+0x1e/0x40\n__kasan_record_aux_stack+0xbe/0xd0\ncall_rcu+0x99/0x740\nnetlink_release+0xe6a/0x1cf0\n__sock_release+0xcd/0x280\nsock_close+0x18/0x20\n__fput+0x27c/0xa90\ntask_work_run+0xdd/0x1a0\nexit_to_user_mode_prepare+0x23c/0x250\nsyscall_exit_to_user_mode+0x19/0x50\ndo_syscall_64+0x42/0x80\nentry_SYSCALL_64_after_hwframe+0x63/0xcd"
  ],
  "references": [
    "https://www.cve.org/CVERecord?id=CVE-2022-49909\nhttps://nvd.nist.gov/vuln/detail/CVE-2022-49909\nhttps://lore.kernel.org/linux-cve-announce/2025050104-CVE-2022-49909-60e6@gregkh/T"
  ]
}